# Generated by Django 4.2.2 on 2023-07-01 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_question_quizze_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='a',
            new_name='A',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='b',
            new_name='B',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='c',
            new_name='C',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='d',
            new_name='D',
        ),
        migrations.RemoveField(
            model_name='quizze',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='app.quizze'),
            preserve_default=False,
        ),
    ]
