# Generated by Django 4.2.2 on 2023-07-01 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_a_question_a_rename_b_question_b_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='quest',
        ),
    ]
