# Generated by Django 4.2.2 on 2023-07-01 17:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_quest_question_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='quizzes',
        ),
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='grade',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='quiz',
            field=models.ForeignKey(default=35, on_delete=django.db.models.deletion.DO_NOTHING, to='app.quizze'),
            preserve_default=False,
        ),
    ]
