# Generated by Django 4.2.2 on 2023-07-01 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_history_quizzes_history_date_history_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.quizze'),
        ),
    ]
